version: '3.9'

services:
  app:
    build: # Use the Dockerfile in the current directory to build the app image
      context: ./animals-api
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb://mongo:27017/animals
    # volumes:
    #   - './animals-api:/app'
    command: "npm run start"
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    volumes:
      - mongodb_data_container:/data/db
    ports:
      - '27017:27017'

  angular_app:
    build: # Use the Dockerfile in the animals-frontend folder to build the angular app image
      context: ./animals-frontend
      dockerfile: Dockerfile
    ports:
      - '4200:4200'
    # volumes:
    #   - './animals-frontend:/app'
    command: "npm start"
    depends_on:
      - app

volumes:
  mongodb_data_container: